require("mdao.plugins-setup")
require("mdao.core.options")
require("mdao.core.keymaps")
require("mdao.core.colorscheme")
require("mdao.plugins.comment")
require("mdao.plugins.nvim-tree")
require("mdao.plugins.lualine")
require("mdao.plugins.telescope")
require("mdao.plugins.nvim-cmp")

